### ISSUE TITLE
Minor changes required to get the kuka repertoires to train and to visualize the kuka experiments

### ISSUE THREAD

**Issue by ErickKramer** [resibots/kaushik_2019_aprol#1]
Hi, 
first of all, thanks for making public your work implementing map-elites with python.

I tried out your repository and found some things that needed to be changed in order to get the kuka repertoires to train and to visualize the kuka experiments:

1. Change absolute paths for relative paths (to work from the base directory) in lines: 
https://github.com/resibots/kaushik_2019_aprol/blob/c69f9301c033cfb89a42ae68aeeb5e65eb8b7fce/kuka_pushing_exps/map_elites_kuka_pushing.py#L70
https://github.com/resibots/kaushik_2019_aprol/blob/c69f9301c033cfb89a42ae68aeeb5e65eb8b7fce/kuka_pushing_exps/map_elites_kuka_pushing.py#L71
https://github.com/resibots/kaushik_2019_aprol/blob/c69f9301c033cfb89a42ae68aeeb5e65eb8b7fce/kuka_pushing_exps/map_elites_kuka_pushing.py#L72

2. `env_params.txt` is missing in each of the *data/kuka_pusher_prior/kuka_pusher_map_toy_n_friction_1/* archives folders. I believe this is caused by `*.txt` being in the `.gitignore` file

---
Recommended changes: 
1. Currently, steps are printed at every run in 
https://github.com/resibots/kaushik_2019_aprol/blob/c69f9301c033cfb89a42ae68aeeb5e65eb8b7fce/environments/kuka_pusher_env.py#L212
I would suggest passing an argument to decide whether steps should be printed or not. 
---
I have already made the changes mentioned above in my forked repository. If you are ok with it, I could create a pull request to yours.

**Comment by riturajkaushik** [comment]
Hey, thanks for reminding. I forgot to correct these absolute paths. And yes, it seems env_params.txt were removed by gitignore. I'll anyways clean the codes a bit very soon and fix the issues.

**Comment by riturajkaushik** [comment]
I have updated the README to avoid the issue with the absolute path to the urdfs. Basically, you need to define an empty environment variable ```RESIBOTS_DIR``` before running the code. Script will automatically take the default paths to the urdfs when this environment variable is available. Regarding ```env_params.txt``` files, these files should not be required to run the examples. 

Can you please confirm if you are able to run the mapelites script for the kuka experiment now?

**Comment by ErickKramer** [comment]
Hey, I cloned again your repo to test the comments you mentioned: 
1. Creating the empty environment variable avoids the need for absolute paths
2. `python3 kuka_pushing_exps/map_elites_kuka_pushing.py --toy 5` can be run without any problem. 
3. `python3 kuka_pushing_exps/kukaPushing_astar_ctlr2cartesian_v2.py --toy 0 --ucb_const 0.5 --kernel_var 0.003 --kernel_l 0.03 --visualization_speed 5.0 --search_size 800 --objectEulerAngles -1 --gui` complains about the missing `env_params.txt`. 

```
Traceback (most recent call last):
  File "kuka_pushing_exps/kukaPushing_astar_ctlr2cartesian_v2.py", line 487, in <module>
    main()
  File "kuka_pushing_exps/kukaPushing_astar_ctlr2cartesian_v2.py", line 289, in main
    with open(dd+"/env_params.txt", 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/kuka_pusher_prior/kuka_pusher_map_toy_10_friction_1/env_params.txt'
```

**Comment by ErickKramer** [comment]
Hey @riturajkaushik, I have a question. 
In https://github.com/resibots/kaushik_2019_aprol/blob/c577eb08d1fff228dd83f4820e8a7d9992cd044d/utils/map_elites.py#L45 where does the 300.0 come from?. Or why did you decide for that value when computing the mutation?. 

Thank you in advance!.

**Comment by riturajkaushik** [comment]
Hey, the 300.0 is actually a hyperparameter for the mutation variance. Since in the original CVT-map elites implementation it was kept like this, so I kept it as well. This value should not impact the optimization that much as long as it keeps the value of  ```(params["max"][i]-params["min"][i])/300.0``` small compared to the range of the parameters. 

You can get the map-elites code from [here](https://github.com/resibots/pymap_elites) if you want to use it for some other purpose.

Regarding the ```env_params.txt``` files, I'll upload them as soon as possible.

**Comment by riturajkaushik** [comment]
Since I lost the original ```env_params.txt``` files for the archives, I had to do a work-around to generate those files based on the information (e.g., friction, blocked legs, toy id etc.) stored in the directory names of the archives. Files are available now.
