### ISSUE TITLE
some questions about experiment

### ISSUE THREAD

**Issue by mw981113zzZ** [resibots/kaushik_2019_aprol#2]
Hi,
first of all, thanks for making public your work implementing map-elites with python. And there is no doubt this's an amazing experiment!
I tired your experiment and found some problems bothers me.

First,**env_params.txt** is missing in each of the **data/hexapod_prior/ archives folders**.If you can, maybe you can upload these.
so that i create **env_params.txt** by myself. It seems work. But If there is no leg damage，i generating the policy repertoires and run the experiment，what should i fill in blocked_legs?

I look forward to your reply and thank you very much！！！

**Comment by mw981113zzZ** [comment]
when i run the **python hexapod_experiments/map_elites_hexapod_cartesian.py --lateral_friction 1.0 --blocked_legs 1 3**,i can get generation0 after 20-30minutes ，but i cannot get others generation after 5-6 hours.I look forward to your reply and thank you very much！！！

**Comment by riturajkaushik** [comment]
For a robot with no damage, blocked_legs is an empty array, e.g., blocked_legs = [ ] .

```env_params.txt``` files are generated when you create a map-elites archive. You do not have to create it manually. 

We created the repertoires on the cluster (no in our laptop). To generate the repertoires in your computer, you have to adjust the map elites parameters accordingly to match the computing power you have. For example, ```"random_init = 3000"``` might take a lot of time if your computer has a small number of cores. Similarly, "dump_period" specifies how often you want to create your archive files. ```dump_period = 1000 ``` means that map-elites will create an archive file after every 1000 generation, where each generation has ```batch_size``` number of evaluations. Our defaults are  ```dump_period = 1000, batch_size=100```. So only after 100,000 evaluations, a new archive will be generated (which a lot for a laptop).  You can try ```dump_period = 10``` or even less to get generate archive files faster.

**Comment by mw981113zzZ** [comment]
Thank you for your reply! I  try your methods and it seems work.

I want to collect data that the legs are not broken，when i run **python hexapod_experiments/map_elites_hexapod_cartesian.py --lateral_friction 1.0 --blocked_legs 1 3** in the terminal,i set the block_legs value with [ ] or blank,it does not work,it seems must set an int value and the system reminds me set at least one argument . Sorry,I don't how to run this and look forward for your reply.

Thanks again for your reply！

**Comment by riturajkaushik** [comment]
Did you try without any ``` --blocked_legs``` argument? i.e., Simply running 
```python
python hexapod_experiments/map_elites_hexapod_cartesian.py --lateral_friction 1.0
```

**Comment by riturajkaushik** [comment]
Also, ```env_params.txt``` files are available now. Let me know if you can run the experiments now.

**Comment by mw981113zzZ** [comment]
Yeah!I try block_legs 1 4 and without block_legs.And this experiments can run well! Thank you for sharing **env_params.txt**.
And thanks again for your reply！

**Comment by riturajkaushik** [comment]
Ok. Great! I am closing this issue.
